version: "3"

services:
  mysql:
    image: mysql
    container_name: base_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
    volumes:
      - "my-vol:/var/lib/mysql"

  api:
    build: ./
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  my-vol: